services:
  console-web:
    build:
      context: /srv/apps/console-web/src
      dockerfile: Dockerfile
    image: console-web:local
    container_name: console-web
    restart: unless-stopped
    networks:
      - proxy
    # env_file:
    #   - .env
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_API_URL=https://console.argos.tld
      - NEXT_PUBLIC_ARGOS_API_BASE=https://api.argos.tld/api
    labels:
      - traefik.enable=true
      - traefik.http.routers.console-web-http.rule=Host(`console.argos.tld`)
      - traefik.http.routers.console-web-http.entrypoints=web
      - traefik.http.routers.console-web.rule=Host(`console.argos.tld`)
      - traefik.http.routers.console-web.entrypoints=websecure
      - traefik.http.routers.console-web.tls=true
      - traefik.http.services.console-web.loadbalancer.server.port=3000

networks:
  proxy:
    external: true
