services:
  api-backend:
    build:
      context: /srv/apps/api-backend/src
      dockerfile: Dockerfile
    image: api-backend:local
    container_name: api-backend
    restart: unless-stopped
    volumes:
      - /srv/configs/api-backend/prod.conf:/config/prod.conf:ro
    networks:
      - proxy
      - data
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - NODE_ENV=production
      - JAVA_TOOL_OPTIONS=-Dconfig.file=/config/prod.conf
    # env_file:
    #   - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.api-backend.rule=Host(`console.argos.tld`) && PathPrefix(`/api`)
      - traefik.http.routers.api-backend.entrypoints=websecure
      - traefik.http.routers.api-backend.tls=true
      - traefik.http.routers.api-backend.priority=100
      - traefik.http.services.api-backend.loadbalancer.server.port=8081


networks:
  proxy:
    external: true
  data:
    external: true
    name: argos-data