services:
  api-backend:
    build:
      context: /srv/apps/api-backend/src
      dockerfile: Dockerfile
    image: api-backend:local
    container_name: api-backend
    restart: unless-stopped
    volumes:
      - /srv/apps/api-backend/prod-test.conf:/config/prod-test.conf:ro
    networks:
      - proxy
      - data
    environment:
      - JAVA_OPTS=-Xms256m -Xmx512m
      - NODE_ENV=production
      - JAVA_TOOL_OPTIONS= -Dconfig.file=/config/prod-test.conf
    # env_file:
    #   - .env
    labels:
      - traefik.enable=true
      - traefik.http.routers.argos-api.rule=Host(`console.argos.tld`) && PathPrefix(`/api`)
      - traefik.http.routers.argos-api.entrypoints=websecure
      - traefik.http.routers.argos-api.tls=true
      - traefik.http.services.argos-api.loadbalancer.server.port=8081

networks:
  proxy:
    external: true
  data:
    external: true
    name: argos-data