name: Deploy (Raspberry)

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Sync sources to /srv/apps
        run: |
          sudo mkdir -p /srv/apps/api-backend/src
          sudo rsync -a --delete ./ /srv/apps/api-backend/src/
          sudo chown -R $USER:$USER /srv/apps/api-backend

      - name: Deploy with Docker Compose (build local)
        run: |
          cd /srv/apps/api-backend
          docker compose -f docker-compose.prod.yml up -d --build --remove-orphans

      - name: Cleanup old images
        run: |
          docker image prune -f
